//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coursepost
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Sort_Desc { get; set; }
        public string Full_Desc { get; set; }
        public string Image { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
