//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeemaster
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Role { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Entereddate { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
